config/routes.rb
Rails.application.routes.draw do
  root to: 'gists#index'

  devise_for :users
  resources :users

  resources :gists
  get '/search' => 'gists#search', as: 'search'
  get '/gists/:id/download' => 'gists#download', as: 'download'

  default_url_options host: 'test.host'
end

app/models/gist.rb
class Gist < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true
  validates :file_name, presence: true
  validates :code, presence: true

  scope :no_secret, -> { where(secret: false) }

  def self.search(search)
    where(secret: false).where("description LIKE ? OR file_name LIKE ? OR code LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gists

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy, :download]

  def index
    @gists = params[:search] ? Gist.search(params[:search]).decorate : Gist.no_secret.decorate
  end

  def show
  end

  def new
    @gist = Gist.new
  end

  def edit
  end

  def create
    @gist = current_user ? current_user.gists.build(gist_params) : Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
  end

  def download
    send_data @gist.code, filename: @gist.file_name
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:description, :file_name, :code, :secret, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_s
      when 'notice' then 'alert alert-info'
      when 'success' then 'alert alert-success'
      when 'error' then 'alert alert-danger'
      when 'alert' then 'alert alert-warning'
    end
  end

  def default_profile_pic_url
    'http://www.isaca.org/SQTComm_Images/profile-default.png'
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.check_box :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gists/_gist.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-6
        p.text-capitalize= gist.description
        = gist.author
        .small= gist.created_at
      .col-md-6
        .pull-right
          = link_to 'Download', download_path(gist.id), class: 'btn btn-danger'
  .panel-body
    = gist.code

app/views/gists/edit.html.erb
<h1>Editing Gist</h1>

<%= render 'form' %>

<%= link_to 'Show', @gist %> |
<%= link_to 'Back', gists_path %>

app/views/gists/index.html.slim
h1= "Listing Gists (#{@gists.count})"

- @gists.each do |gist|
  = render partial: 'gist', locals: {gist: gist}

app/views/gists/new.html.erb
<h1>New Gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path %>

app/views/gists/search.html.slim
= form_tag(gists_path, method: 'get', id: 'search-form') do
  = text_field_tag :search, params[:search], placeholder: 'Search Gists'
  = submit_tag 'Search', class: 'btn btn-primary'

app/views/gists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @gist.description %>
</p>

<p>
  <strong>File name:</strong>
  <%= @gist.file_name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @gist.code %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @gist.secret %>
</p>

<p>
  <strong>User:</strong>
  <%= @gist.user_id %>
</p>

<%= link_to 'Edit', edit_gist_path(@gist) %> |
<%= link_to 'Back', gists_path %>

app/views/home/index.html.slim
h1
  'Welcome in the GistApp

app/views/layouts/_footer.html.slim
.footer
  .row
    .col-md-6.col-md-offset-3.text-center
      '&copy;
      = "#{Time.now.year}  GISTAPP"

app/views/layouts/_header.html.slim
nav.navbar.navbar-fixed-top
  .container
    .navbar-header
      .navbar-brand
        = link_to 'GISTAPP', root_path

    ul.nav.navbar-nav.navbar-right
      li
        = link_to 'Search', search_path
      li
        = link_to 'Create Gist', new_gist_path
      li.dropdown
        - if user_signed_in?
          = link_to '#', { "data-toggle" => "dropdown" } do
            i.icon-user
              = current_user.first_name
            b.caret
          ul.dropdown-menu
            li
              = link_to 'Dashboard', user_path(current_user)
            li
              = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          = link_to 'Login', new_user_session_path

.row
  .col-md-6.col-md-offset-3
    = render 'shared/flash_alert'

app/views/layouts/application.html.slim
doctype html
html[lang='en']
  head
    meta charset='utf-8'
    meta content='IE=edge' http-equiv='X-UA-Compatible'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title = 'GistApp'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .row
      .col-md-6.col-md-offset-3
        = yield
    = render 'layouts/footer'
    = javascript_include_tag 'application'

app/views/shared/_flash_alert.html.slim
- flash.each do |key, value|
  div class=("alert alert-dismissable #{flash_class(key)} right fade in")
    button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
    = value.html_safe unless value.nil?

app/views/users/show.html.slim
h1= @user.first_name
h2= @user.last_name